const actionType = {
  TOGGLE_LOGIN: "TOGGLE_LOGIN",
  SHOW_QUICK_VIEW: "SHOW_QUICK_VIEW",
  HIDE_QUICK_VIEW: "HIDE_QUICK_VIEW",
  TOGGLE_WISHLIST: "TOGGLE_WISHLIST",
  FETCH_WISHLIST: "FETCH_WISHTLIST",
};

export default actionType;
